import AlertDialog from "@/components/AlertDialog";
import Loading from "@/components/Loading";
import { setData } from "@/stores/counterSlice";
import { useQuery } from "@tanstack/react-query";
import axios from "axios";
import Head from "next/head";
import Link from "next/link";
import { useDispatch } from "react-redux";

export default function Home() {
  const dispatch = useDispatch();
  const getTodos = async () => {
    const { data } = await axios.get("/reviews");
    return data;
  };
  const { data, isLoading, error } = useQuery({
    queryKey: ["todos"],
    queryFn: getTodos,
  });

  console.log(data);
  dispatch(setData(data));

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {isLoading && <Loading></Loading>}
      {error && <AlertDialog />}
      <main>
        <div>test</div>
        <Link href={"/sample"}>sample</Link>
      </main>
    </>
  );
}
