import { useMutation, useQuery } from '@tanstack/react-query'
import axios from 'axios'
import Head from 'next/head'
import Link from 'next/link'
import { useDispatch } from 'react-redux'
import AlertDialog from '@/components/AlertDialog'
import Loading from '@/components/Loading'
import useApi from '@/hooks/useApi'
import { setData } from '@/stores/counterSlice'
import { ModelName } from '@/types/api'

export default function Home() {
  const dispatch = useDispatch()
  const { data } = useApi(ModelName.ALEXNET)

  const { mutate } = useMutation({
    mutationFn: (name) => axios.post('/item', { name: name }),
  })

  // console.log(data);
  // dispatch(setData(data));

  const createItem = () => {
    mutate()
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {/* {isLoading && <Loading></Loading>}
      {error && <AlertDialog />} */}
      <main>
        <div className='bg-base p-2'>
          <div>
            <p className='text-primary'>primary</p>
            <p className='text-secondary'>secondary</p>
          </div>
          <div className='space-x-2'>
            <button className='rounded bg-primary px-4 py-2 font-bold text-white'>Primary</button>
            <button className='rounded bg-secondary px-4 py-2 font-bold text-white'>Secondary</button>
          </div>
        </div>
        <div className=''>
          <div>
            <Link href={'/sample'} className='text-primary'>
              sample
            </Link>
          </div>
          <button className='rounded bg-primary px-4 py-2 font-bold text-white' onClick={createItem}>
            create item
          </button>
        </div>
      </main>
    </>
  )
}
